CASMPET-6798: Update Spire OPA Policy for SBPS Marshal Agent
Cray-HPE/cray-opa pull request #105
Opened 2024-01-24 08:25 UTC by ravikanth-nalla-hpe

- enable OPA policy for SBPS marshal agent

## Summary and Scope

Need to update/ enable Spire OPA Policy for new SBPS Marshal Agent w.r.t iscsi based boot content projection.

## Issues and Related PRs

_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._

## Testing

Tested on Mug and Noname systems.

### Tested on:

Tested on Mug and Noname systems.

### Test description:

_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_

- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? yet to run in upgrade scenario
- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test issues/Jiras) created for this change?

## Risks and Mitigations
None.

## Pull Request Checklist

- [x ] Version number(s) incremented, if applicable
- [x] Copyrights updated
- [ ] License file intact
- [x] Target branch correct
- [ ] CHANGELOG.md updated
- [x] Testing is appropriate and complete, if applicable
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2024-01-26 04:36 UTC, jeremy-duckworth commented
Please switch this from a draft to published PR.

2024-01-26 04:37 UTC, jeremy-duckworth requested changes
You need to add a unit test for this modification. See the other spire examples and reach out if needed. Thanks.

2024-03-05 14:11 UTC, jeremy-duckworth requested changes

2024-03-05 14:11 UTC, jeremy-duckworth commented on kubernetes/cray-opa/templates/policies/spire.yaml
> +          {"method": "GET", "path": sprintf("^/apis/ims/v3/images/%v$", [parsed_spire_token.xname])},
The IMS API doesn't have an xname as part of the API path here. Suggest simply taking the templated if out and using a static definition.

2024-03-21 14:25 UTC, jeremy-duckworth approved these changes

2024-03-21 15:09 UTC, ndavidson-hpe approved these changes

2024-03-21 20:30 UTC, merged